# Project: Tubes2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o body.o Tendy.o menu.o
LINKOBJ  = main.o body.o Tendy.o menu.o
LIBS     = -L"D:/Ikhsan/coding/Dev-Cpp/MinGW64/lib" -L"D:/Ikhsan/coding/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/include" -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/include" -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Ikhsan/coding/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Tubes2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

body.o: body.c
	$(CC) -c body.c -o body.o $(CFLAGS)

Tendy.o: Tendy.c
	$(CC) -c Tendy.c -o Tendy.o $(CFLAGS)

menu.o: menu.c
	$(CC) -c menu.c -o menu.o $(CFLAGS)
